[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mysqli", "php82Extensions.pdo"]

[phases.build]
cmds = ["cp php.ini /etc/php.ini"]

[start]
cmd = "php -S 0.0.0.0:$PORT -c php.ini"
